db:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=kegstarter
    - POSTGRES_PASSWORD=kegstarter
  expose:
    - "5432"

backend:
  build: backend
  command: manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  volumes:
    - ./backend:/opt/backend
  links:
    - db

frontend:
  build: frontend
  command: ember serve
  ports:
    - "8080:8080"
  volumes:
    - .:/code
  links:
    - backend
